credentials:
  usernames:
    yerkosapiens:
      email: yerkosapiens@gmail.com
      name: John Smith
      password: abc # To be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: def # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: gdfg456456gdgdgSS # Must be string
  name: cockie_winxa
preauthorized:
  emails:
  - yerkosapiens@gmail.com